# Generated by Django 2.1.5 on 2025-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlandWanderer', '0002_auto_20250318_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
